language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

before_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi


script:
    - travis/run-phpunit.sh $TRAVIS_PHP_VERSION
